In [3]:
# Consider following code to answer further questions:
import pandas as pd
course_name = ['Data Science', 'Machine Learning', 'Big Data', 'Data Engineer']
duration = [2,3,6,4]
df = pd.DataFrame(data = {'course_name' : course_name, 'duration' : duration})

In [4]:
df.head()

        course_name  duration
0      Data Science         2
1  Machine Learning         3
2          Big Data         6
3     Data Engineer         4

In [6]:
# Q1. Write a code to print the data present in the second row of the dataframe, df.
df.iloc[1]

course_name    Machine Learning
duration                      3
Name: 1, dtype: object

In [ ]:
# Q2. What is the difference between the functions loc and iloc in pandas.DataFrame?
'''
The loc() function is label based data selecting method which means that we have to pass the name of the row or column which we want to select.
This method includes the last element of the range passed in it, unlike iloc(). loc() can accept the boolean data unlike iloc().'''

'\nThe loc() function is label based data selecting method which means that we have to pass the name of the row or column which we want to select.\nThis method includes the last element of the range passed in it, unlike iloc(). loc() can accept the boolean data unlike iloc().'

In [7]:
# Q3. Reindex the given dataframe using a variable, reindex = [3,0,1,2] and store it in the variable, new_df then find the output for both new_df.loc[2] and new_df.iloc[2].
# Did you observe any difference in both the outputs? If so then explain it.

# New index labels
new_index = [3, 0, 1, 2]  # You can specify the desired order of rows

# Reindex the DataFrame based on the new index
df_reindexed = df.reindex(new_index)

df_reindexed , df               #so we can see thee diffefernce of the indexing in this dataset

(        course_name  duration
 3     Data Engineer         4
 0      Data Science         2
 1  Machine Learning         3
 2          Big Data         6,
         course_name  duration
 0      Data Science         2
 1  Machine Learning         3
 2          Big Data         6
 3     Data Engineer         4)

In [8]:
# Consider the below code to answer further questions:
import pandas as pd
import numpy as np
columns = ['column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6']
indices = [1,2,3,4,5,6]
#Creating a dataframe:
df1 = pd.DataFrame(np.random.rand(6,6), columns = columns, index = indices)

In [9]:
df1

   column_1  column_2  column_3  column_4  column_5  column_6
1  0.839155  0.754072  0.256248  0.626262  0.275522  0.345117
2  0.686820  0.608532  0.688306  0.861479  0.109907  0.589126
3  0.378775  0.958920  0.906584  0.106285  0.139593  0.582518
4  0.488032  0.902858  0.818468  0.532150  0.388767  0.576340
5  0.830197  0.656856  0.707766  0.135274  0.416486  0.754366
6  0.756083  0.280226  0.731939  0.887214  0.020043  0.905212

In [10]:
# Q4. Write a code to find the following statistical measurements for the above dataframe df1:
# (i) mean of each and every column present in the dataframe.
# (ii) standard deviation of column, ‘column_2’

mean_dataframe=np.mean(df1)
standard_deviation_of_dataframe=np.std(df1["column_2"])
print(f"the mean of this dataframe are: .\n{mean_dataframe}.\n")
print(f"the standard deviation of this dataframe are: {standard_deviation_of_dataframe}.\n")

the mean of this dataframe are: .
column_1    0.663177
column_2    0.693577
column_3    0.684885
column_4    0.524777
column_5    0.225053
column_6    0.625446
dtype: float64.

the standard deviation of this dataframe are: 0.2226000706497784.

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

In [11]:
# Q5. Replace the data present in the second row of column, ‘column_2’ by a string variable then find the
# mean of column, column_2.
# If you are getting errors in executing it then explain why.
# [Hint: To replace the data use df1.loc[] and equate this to string data of your choice.]
import pandas as pd
import numpy as np

columns = ['column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6']
indices = [1, 2, 3, 4, 5, 6]

# Creating a DataFrame
df1 = pd.DataFrame(np.random.rand(6, 6), columns=columns, index=indices)

# Replace the data in the second row of 'column_2' with a string value
replacement_string = 'ReplacedString'
df1.loc[2, 'column_2'] = replacement_string

# Convert 'column_2' to a compatible numeric data type
df1['column_2'] = pd.to_numeric(df1['column_2'], errors='coerce')

# Calculate the mean of 'column_2'
mean_column_2 = df1['column_2'].mean()

print("DataFrame after replacing the data:")
print(df1)
print("\nMean of 'column_2':", mean_column_2)

DataFrame after replacing the data:
   column_1  column_2  column_3  column_4  column_5  column_6
1  0.738427  0.178531  0.542411  0.612061  0.578616  0.774996
2  0.449028       NaN  0.466142  0.871434  0.595584  0.444120
3  0.903721  0.851068  0.713263  0.321105  0.493572  0.658236
4  0.340297  0.804956  0.556117  0.633460  0.266902  0.148363
5  0.013664  0.867433  0.109557  0.562619  0.362700  0.999817
6  0.641895  0.252377  0.301449  0.986082  0.551935  0.007204

Mean of 'column_2': 0.5908727412011958

In [12]:
# Q6. What do you understand about the windows function in pandas and list the types of windows functions?

'''
In Pandas, window functions (also known as rolling or moving functions) are used to perform calculations over a specified "window" or range of values in a DataFrame or Series. These functions are particularly useful for time-series analysis and other scenarios where you want to compute aggregated values over a moving set of data points. Window functions allow you to perform operations like moving averages, rolling sums, and more.

Window functions work by applying a function to a subset of data defined by a sliding window. The size of the window can be specified using a fixed number of periods or a time-based offset.

Here are some common types of window functions available in Pandas:

1. **Rolling Functions:**
   These functions operate over a rolling window of a fixed number of periods. They are particularly useful for time-series data.
   - `rolling().mean()`: Calculate the rolling mean.
   - `rolling().sum()`: Calculate the rolling sum.
   - `rolling().min()`: Calculate the rolling minimum.
   - `rolling().max()`: Calculate the rolling maximum.

2. **Expanding Functions:**
   These functions expand the window size over time. Each calculation includes all data up to the current position.
   - `expanding().mean()`: Calculate the expanding mean.
   - `expanding().sum()`: Calculate the expanding sum.
   - `expanding().min()`: Calculate the expanding minimum.
   - `expanding().max()`: Calculate the expanding maximum.

3. **Exponential Moving Average (EMA):**
   This is a weighted moving average where more recent data points are given higher weights.
   - `ewm().mean()`: Calculate the exponential moving average.

4. **Window Aggregations:**
   These functions perform custom aggregation operations on a window.
   - `rolling().apply(func)`: Apply a custom function to the rolling window.
   - `expanding().apply(func)`: Apply a custom function to the expanding window.

5. **Ranking Functions:**
   These functions compute the ranking of elements within a window.
   - `rolling().rank()`: Compute the rank of elements in a rolling window.
   - `expanding().rank()`: Compute the rank of elements in an expanding window.

6. **Shift and Lag Functions:**
   These functions allow you to access data from previous or future periods.
   - `shift()`: Shift the values of a Series by a specified number of periods.
   - `diff()`: Compute the difference between consecutive values.
   - `pct_change()`: Compute the percentage change between consecutive values.

These are just some of the window functions available in Pandas.
 Window functions provide powerful tools for analyzing and processing time-series and sequential data in a flexible and efficient manner.'''

'\nIn Pandas, window functions (also known as rolling or moving functions) are used to perform calculations over a specified "window" or range of values in a DataFrame or Series. These functions are particularly useful for time-series analysis and other scenarios where you want to compute aggregated values over a moving set of data points. Window functions allow you to perform operations like moving averages, rolling sums, and more.\n\nWindow functions work by applying a function to a subset of data defined by a sliding window. The size of the window can be specified using a fixed number of periods or a time-based offset.\n\nHere are some common types of window functions available in Pandas:\n\n1. **Rolling Functions:**\n   These functions operate over a rolling window of a fixed number of periods. They are particularly useful for time-series data.\n   - `rolling().mean()`: Calculate the rolling mean.\n   - `rolling().sum()`: Calculate the rolling sum.\n   - `rolling().min()`: Calculate the rolling minimum.\n   - `rolling().max()`: Calculate the rolling maximum.\n\n2. **Expanding Functions:**\n   These functions expand the window size over time. Each calculation includes all data up to the current position.\n   - `expanding().mean()`: Calculate the expanding mean.\n   - `expanding().sum()`: Calculate the expanding sum.\n   - `expanding().min()`: Calculate the expanding minimum.\n   - `expanding().max()`: Calculate the expanding maximum.\n\n3. **Exponential Moving Average (EMA):**\n   This is a weighted moving average where more recent data points are given higher weights.\n   - `ewm().mean()`: Calculate the exponential moving average.\n\n4. **Window Aggregations:**\n   These functions perform custom aggregation operations on a window.\n   - `rolling().apply(func)`: Apply a custom function to the rolling window.\n   - `expanding().apply(func)`: Apply a custom function to the expanding window.\n\n5. **Ranking Functions:**\n   These functions compute the ranking of elements within a window.\n   - `rolling().rank()`: Compute the rank of elements in a rolling window.\n   - `expanding().rank()`: Compute the rank of elements in an expanding window.\n\n6. **Shift and Lag Functions:**\n   These functions allow you to access data from previous or future periods.\n   - `shift()`: Shift the values of a Series by a specified number of periods.\n   - `diff()`: Compute the difference between consecutive values.\n   - `pct_change()`: Compute the percentage change between consecutive values.\n\nThese are just some of the window functions available in Pandas.\n Window functions provide powerful tools for analyzing and processing time-series and sequential data in a flexible and efficient manner.'

In [13]:
# Q7. Write a code to print only the current month and year at the time of answering this question.
# [Hint: Use pandas.datetime function]

import pandas as pd
from datetime import datetime

# Get the current date and time
current_date_time = datetime.now()

# Extract the current month and year
current_month = current_date_time.month
current_year = current_date_time.year

# Print the current month and year
print("Current Month:", current_month)
print("Current Year:", current_year)
# print("Current day:", current_date_time.day)

Current Month: 8
Current Year: 2023

In [14]:
# Q8. Write a Python program that takes in two dates as input (in the format YYYY-MM-DD) and calculates the difference between them in days,
# hours, and minutes using Pandas time delta. The program should prompt the user to enter the dates and display the result.

import pandas as pd

# Input dates in YYYY-MM-DD format
date1 = input("Enter the first date (YYYY-MM-DD): ")
date2 = input("Enter the second date (YYYY-MM-DD): ")

# Convert input strings to Pandas datetime objects
date1 = pd.to_datetime(date1)
date2 = pd.to_datetime(date2)

# Calculate the time difference using Timedelta
time_difference = date2 - date1

# Extract days, hours, and minutes from the time difference
days = time_difference.days
hours = time_difference.seconds // 3600
minutes = (time_difference.seconds // 60) % 60



# Display the result
print("Time Difference:")
print(f"Days: {days}")
print(f"Hours: {hours}")
print(f"Minutes: {minutes}")

Enter the first date (YYYY-MM-DD): 1999-08-24
Enter the second date (YYYY-MM-DD): 2023-08-24
Time Difference:
Days: 8766
Hours: 0
Minutes: 0

In [17]:
df=pd.read_csv("googleplaystore.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [19]:
# Q9. Write a Python program that reads a CSV file containing categorical data and converts a specified
# column to a categorical data type. The program should prompt the user to enter the file path, column
# name, and category order, and then display the sorted data.

import pandas as pd

# Input file path, column name, and category order
file_path = input("Enter the CSV file path: ")
column_name = input("Enter the column name to convert to categorical: ")
category_order = input("Enter the category order (comma-separated): ").split(',')

# Read the CSV file into a DataFrame
data = pd.read_csv(file_path)

# Convert the specified column to categorical
data[column_name] = pd.Categorical(data[column_name], categories=category_order, ordered=True)

# Sort the DataFrame based on the specified column
sorted_data = data.sort_values(by=[column_name])

# Display the sorted data
print("\nSorted Data:")
print(sorted_data)

Enter the CSV file path: /content/googleplaystore.csv
Enter the column name to convert to categorical: Size
Enter the category order (comma-separated): .

Sorted Data:
                                                     App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN
3                                  Sketch - Draw & Paint       ART_AND_DESIGN
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN
...                                                  ...                  ...
10836                                   Sya9a Maroc - FR               FAMILY
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY
10838                             Parkinson Exercices FR              MEDICAL
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews Size     Installs  Type Price Content Rating  \
0         4.1     159  NaN      10,000+  Free     0       Everyone
1         3.9     967  NaN     500,000+  Free     0       Everyone
2         4.7   87510  NaN   5,000,000+  Free     0       Everyone
3         4.5  215644  NaN  50,000,000+  Free     0           Teen
4         4.3     967  NaN     100,000+  Free     0       Everyone
...       ...     ...  ...          ...   ...   ...            ...
10836     4.5      38  NaN       5,000+  Free     0       Everyone
10837     5.0       4  NaN         100+  Free     0       Everyone
10838     NaN       3  NaN       1,000+  Free     0       Everyone
10839     4.5     114  NaN       1,000+  Free     0     Mature 17+
10840     4.5  398307  NaN  10,000,000+  Free     0       Everyone

                          Genres      Last Updated         Current Ver  \
0                   Art & Design   January 7, 2018               1.0.0
1      Art & Design;Pretend Play  January 15, 2018               2.0.0
2                   Art & Design    August 1, 2018               1.2.4
3                   Art & Design      June 8, 2018  Varies with device
4        Art & Design;Creativity     June 20, 2018                 1.1
...                          ...               ...                 ...
10836                  Education     July 25, 2017                1.48
10837                  Education      July 6, 2018                 1.0
10838                    Medical  January 20, 2017                 1.0
10839          Books & Reference  January 19, 2015  Varies with device
10840                  Lifestyle     July 25, 2018  Varies with device

              Android Ver
0            4.0.3 and up
1            4.0.3 and up
2            4.0.3 and up
3              4.2 and up
4              4.4 and up
...                   ...
10836          4.1 and up
10837          4.1 and up
10838          2.2 and up
10839  Varies with device
10840  Varies with device

[10841 rows x 13 columns]

In [ ]:
# Q10. Write a Python program that reads a CSV file containing sales data for different products and
# visualizes the data using a stacked bar chart to show the sales of each product category over time. The
# program should prompt the user to enter the file path and display the chart.

In [23]:
df=pd.read_csv("Salesforce_stock_history.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4385 entries, 0 to 4384
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          4385 non-null   object
 1   Open          4385 non-null   float64
 2   High          4385 non-null   float64
 3   Low           4385 non-null   float64
 4   Close         4385 non-null   float64
 5   Volume        4385 non-null   int64
 6   Dividends     4385 non-null   int64
 7   Stock Splits  4385 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 274.2+ KB

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Input file path
file_path = input("Enter the CSV file path: ")

# Read the CSV file into a DataFrame
data = pd.read_csv(file_path)

# Convert the 'Date' column to datetime
data['Date'] = pd.to_datetime(data['Date'])

# Pivot the data to create a DataFrame suitable for stacked bar chart
pivot_data = data.pivot(index='Date', columns='High', values='Low')

# Plot the stacked bar chart
pivot_data.plot(kind='bar', stacked=True, figsize=(10, 6))
plt.title('Sales by Product Category Over Time')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.xticks(rotation=45)
plt.legend(title='Product Category')

# Show the chart
plt.show()

Enter the CSV file path: /content/Salesforce_stock_history.csv

In [ ]:
'''
Q11. You are given a CSV file containing student data that includes the student ID and their test score. Write
a Python program that reads the CSV file, calculates the mean, median, and mode of the test scores, and
displays the results in a table.
The program should do the followingM
I Prompt the user to enter the file path of the CSV file containing the student dataR
I Read the CSV file into a Pandas DataFrameR
I Calculate the mean, median, and mode of the test scores using Pandas toolsR
I Display the mean, median, and mode in a table.
Assume the CSV file contains the following columnsM
I Student ID: The ID of the studentR
I Test Score: The score of the student's test.
Example usage of the program:
Enter the file path of the CSV file containing the student data: student_data.csv
+-----------+--------+
| Statistic | Value |
+-----------+--------+
| Mean | 79.6 |
| Median | 82 |
| Mode | 85, 90 |
+-----------+--------+
Assume that the CSV file student_data.csv contains the following data:
Student ID,Test Score
1,85
2,90
3,80
4,75
5,85
6,82
7,78
8,85
9,90
10,85'''

In [ ]:
Student_ID = ['10145', '18569', '15360', '10025']
Test_Score = [82,93,66,74]
student_data= pd.DataFrame(data = {'Student_ID' : Student_ID, 'Test_Score' : Test_Score})
df.to_csv('student_data.csv')
student_data

  Student_ID  Test_Score
0      10145          82
1      18569          93
2      15360          66
3      10025          74

In [ ]:
import pandas as pd
from scipy import stats

# Prompt the user to enter the file path
file_path = input("Enter the file path of the CSV file containing the student data: ")

# Read the CSV file into a DataFrame
student_data = pd.read_csv(file_path)

# Calculate the mean, median, and mode of test scores
mean_score = student_data['Test Score'].mean()
median_score = student_data['Test Score'].median()
mode_scores = stats.mode(student_data['Test Score'])[0]  # Returns an array of mode values

# Display the results in a table
result_table = pd.DataFrame({
    'Statistic': ['Mean', 'Median', 'Mode'],
    'Value': [mean_score, median_score, ', '.join(map(str, mode_scores))]
})

print(result_table)

Enter the file path of the CSV file containing the student data: /content/student_data.csv

KeyError: ignored